// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDW3gJgeTGrlieNDz3lJj-I6Ygze7OZM',
    appId: '1:484281140827:web:68323a7101981c09aea17e',
    messagingSenderId: '484281140827',
    projectId: 'insaf-somiti',
    authDomain: 'insaf-somiti.firebaseapp.com',
    storageBucket: 'insaf-somiti.firebasestorage.app',
    measurementId: 'G-FRNE7HCD39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbo90LPAOCB6JEpOLUCOD6ktz9BuSf-xM',
    appId: '1:484281140827:android:f04d7c7b4cefa5e0aea17e',
    messagingSenderId: '484281140827',
    projectId: 'insaf-somiti',
    storageBucket: 'insaf-somiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8d6WnrAqElrG1XsbVv9r8b0H5baGYO2g',
    appId: '1:484281140827:ios:39e2cc5679860193aea17e',
    messagingSenderId: '484281140827',
    projectId: 'insaf-somiti',
    storageBucket: 'insaf-somiti.firebasestorage.app',
    iosBundleId: 'com.example.insafSomiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8d6WnrAqElrG1XsbVv9r8b0H5baGYO2g',
    appId: '1:484281140827:ios:39e2cc5679860193aea17e',
    messagingSenderId: '484281140827',
    projectId: 'insaf-somiti',
    storageBucket: 'insaf-somiti.firebasestorage.app',
    iosBundleId: 'com.example.insafSomiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDW3gJgeTGrlieNDz3lJj-I6Ygze7OZM',
    appId: '1:484281140827:web:4563de5a35cabe73aea17e',
    messagingSenderId: '484281140827',
    projectId: 'insaf-somiti',
    authDomain: 'insaf-somiti.firebaseapp.com',
    storageBucket: 'insaf-somiti.firebasestorage.app',
    measurementId: 'G-VLPKMV1JGE',
  );
}
